# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmE7gbJDFC2HwJgTrsB0S0Uegu4X_vue
"""

from google.colab.patches import cv2_imshow
import cv2
import numpy as np

RATIO = 0.75

def load_gray(path: str):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"No se pudo cargar la imagen: {path}")
    return img

def ratio_test_knn(knn_matches, ratio=0.75):
    """Filtra matches usando Lowe's ratio test.
    Mantiene m si m.distance < ratio * n.distance
    """
    good = []
    for pair in knn_matches:
        if len(pair) < 2:
            continue
        m, n = pair[0], pair[1]
        if m.distance < ratio * n.distance:
            good.append(m)
    return good

def sift_pipeline(img1, img2):
    sift = cv2.SIFT_create()
    kp1, des1 = sift.detectAndCompute(img1, None)
    kp2, des2 = sift.detectAndCompute(img2, None)

    if des1 is None or des2 is None or len(kp1) == 0 or len(kp2) == 0:
        raise RuntimeError("SIFT no encontró suficientes keypoints/descriptores.")

    bf = cv2.BFMatcher(cv2.NORM_L2, crossCheck=False)
    knn = bf.knnMatch(des1, des2, k=2)

    good = ratio_test_knn(knn, ratio=RATIO)

    out = cv2.drawMatches(
        img1, kp1,
        img2, kp2,
        good, None,
        flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
    )

    return out, kp1, kp2, good

def orb_pipeline(img1, img2, nfeatures=2000):
    orb = cv2.ORB_create(nfeatures=nfeatures)
    kp1, des1 = orb.detectAndCompute(img1, None)
    kp2, des2 = orb.detectAndCompute(img2, None)

    if des1 is None or des2 is None or len(kp1) == 0 or len(kp2) == 0:
        raise RuntimeError("ORB no encontró suficientes keypoints/descriptores.")

    bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=False)
    knn = bf.knnMatch(des1, des2, k=2)

    good = ratio_test_knn(knn, ratio=RATIO)

    out = cv2.drawMatches(
        img1, kp1,
        img2, kp2,
        good, None,
        flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
    )

    return out, kp1, kp2, good

def main():
    path1 = "img01.jpeg"
    path2 = "img02.jpeg"

    img1 = load_gray(path1)
    img2 = load_gray(path2)

    sift_vis, kp1_s, kp2_s, good_s = sift_pipeline(img1, img2)
    print(f"[SIFT] Keypoints img1: {len(kp1_s)} | img2: {len(kp2_s)} | Good matches: {len(good_s)}")

    orb_vis, kp1_o, kp2_o, good_o = orb_pipeline(img1, img2, nfeatures=2000)
    print(f"[ORB ] Keypoints img1: {len(kp1_o)} | img2: {len(kp2_o)} | Good matches: {len(good_o)}")

    cv2_imshow(sift_vis)
    cv2_imshow(orb_vis)


    cv2.imwrite("resultado_sift_matches.jpg", sift_vis)
    cv2.imwrite("resultado_orb_matches.jpg", orb_vis)

if __name__ == "__main__":
    main()