# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmE7gbJDFC2HwJgTrsB0S0Uegu4X_vue
"""

from google.colab.patches import cv2_imshow
import cv2
import numpy as np
import time

RATIO = 0.75
N_RUNS = 20

def load_gray(path: str):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"No se pudo cargar la imagen: {path}")
    return img

def ratio_test_knn(knn_matches, ratio=0.75):
    good = []
    for pair in knn_matches:
        if len(pair) < 2:
            continue
        m, n = pair[0], pair[1]
        if m.distance < ratio * n.distance:
            good.append(m)
    return good

def ms(x_seconds: float) -> float:
    return x_seconds * 1000.0

def time_sift(img1, img2, runs=20):
    sift = cv2.SIFT_create()
    bf = cv2.BFMatcher(cv2.NORM_L2, crossCheck=False)

    detdesc_times = []
    match_times = []
    last_good = None
    last_kp1 = last_kp2 = None

    for _ in range(runs):
        t0 = time.perf_counter()
        kp1, des1 = sift.detectAndCompute(img1, None)
        kp2, des2 = sift.detectAndCompute(img2, None)
        t1 = time.perf_counter()

        if des1 is None or des2 is None or len(kp1) == 0 or len(kp2) == 0:
            continue

        t2 = time.perf_counter()
        knn = bf.knnMatch(des1, des2, k=2)
        good = ratio_test_knn(knn, ratio=RATIO)
        t3 = time.perf_counter()

        detdesc_times.append(ms(t1 - t0))
        match_times.append(ms(t3 - t2))

        last_good = good
        last_kp1, last_kp2 = kp1, kp2

    return {
        "detdesc_ms_avg": float(np.mean(detdesc_times)) if detdesc_times else None,
        "match_ms_avg": float(np.mean(match_times)) if match_times else None,
        "kp1": len(last_kp1) if last_kp1 is not None else 0,
        "kp2": len(last_kp2) if last_kp2 is not None else 0,
        "good_matches": len(last_good) if last_good is not None else 0,
        "last_good": last_good,
        "last_kp1": last_kp1,
        "last_kp2": last_kp2
    }

def time_orb(img1, img2, runs=20, nfeatures=2000):
    orb = cv2.ORB_create(nfeatures=nfeatures)
    bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=False)

    detdesc_times = []
    match_times = []
    last_good = None
    last_kp1 = last_kp2 = None

    for _ in range(runs):
        t0 = time.perf_counter()
        kp1, des1 = orb.detectAndCompute(img1, None)
        kp2, des2 = orb.detectAndCompute(img2, None)
        t1 = time.perf_counter()

        if des1 is None or des2 is None or len(kp1) == 0 or len(kp2) == 0:
            continue

        t2 = time.perf_counter()
        knn = bf.knnMatch(des1, des2, k=2)
        good = ratio_test_knn(knn, ratio=RATIO)
        t3 = time.perf_counter()

        detdesc_times.append(ms(t1 - t0))
        match_times.append(ms(t3 - t2))

        last_good = good
        last_kp1, last_kp2 = kp1, kp2

    return {
        "detdesc_ms_avg": float(np.mean(detdesc_times)) if detdesc_times else None,
        "match_ms_avg": float(np.mean(match_times)) if match_times else None,
        "kp1": len(last_kp1) if last_kp1 is not None else 0,
        "kp2": len(last_kp2) if last_kp2 is not None else 0,
        "good_matches": len(last_good) if last_good is not None else 0,
        "last_good": last_good,
        "last_kp1": last_kp1,
        "last_kp2": last_kp2
    }

def main():
    path1 = "img01.jpeg"
    path2 = "img02.jpeg"

    img1 = load_gray(path1)
    img2 = load_gray(path2)

    sift_stats = time_sift(img1, img2, runs=N_RUNS)
    print("\n=== SIFT Timing ===")
    print(f"Detección+Descripción (ms promedio): {sift_stats['detdesc_ms_avg']:.3f}")
    print(f"Matching+RatioTest (ms promedio):   {sift_stats['match_ms_avg']:.3f}")
    print(f"Keypoints img1: {sift_stats['kp1']} | img2: {sift_stats['kp2']} | Good matches: {sift_stats['good_matches']}")

    orb_stats = time_orb(img1, img2, runs=N_RUNS, nfeatures=2000)
    print("\n=== ORB Timing ===")
    print(f"Detección+Descripción (ms promedio): {orb_stats['detdesc_ms_avg']:.3f}")
    print(f"Matching+RatioTest (ms promedio):   {orb_stats['match_ms_avg']:.3f}")
    print(f"Keypoints img1: {orb_stats['kp1']} | img2: {orb_stats['kp2']} | Good matches: {orb_stats['good_matches']}")

    sift_vis = cv2.drawMatches(
        img1, sift_stats["last_kp1"],
        img2, sift_stats["last_kp2"],
        sift_stats["last_good"], None,
        flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
    )
    orb_vis = cv2.drawMatches(
        img1, orb_stats["last_kp1"],
        img2, orb_stats["last_kp2"],
        orb_stats["last_good"], None,
        flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
    )

    cv2.imwrite("timing_sift_matches.jpg", sift_vis)
    cv2.imwrite("timing_orb_matches.jpg", orb_vis)

    cv2_imshow(sift_vis)
    cv2_imshow(orb_vis)

if __name__ == "__main__":
    main()